name: Auto message on Creating Issue.

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - name: Create comment for issue
      if: github.event_name =='issues' 
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{tojson(github.event.issue.number)}}
        body: |
            Hi 😄, @${{ github.actor }} Thanks for creating  issue at Code Crossroad, do read and follow the  [Contribution Guidelines]() while contributing. Refer to PR's which has been merged earlier in Code Crossroad [Click Here]() Like, How many File they have changed?, Which type of files need to be change? and many more.
    
    
    
    
    
